name: Node.js App Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Repository
      uses: actions/checkout@v2

    - name: Execute setup_environment.sh
      run: |
        chmod +x setup_environment.sh
        ./setup_environment.sh
        chmod +x key.pem

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USERNAME }}
        key: |
          echo "$(<key.pem)"
        script: |
          ./pull_repo.sh
          cd /app
          npm install
          pm2 restart app.js