name: Node.js App Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        chmod +x write_key.sh
        ./write_key.sh
        chmod +x key.pem
        chmod +x export_variables.sh
        export $(./export_variables.sh)

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USERNAME }}
        key: |
          echo "$(<key.pem)"
        script: |
          ./pull_repo.sh
          cd /app
          npm install
          pm2 restart app.js