name: Node.js App Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        chmod +x write_key.sh
        ./write_key.sh
        chmod 600 key.pem
        openssl rsa -in key.pem -check

    - name: Deploy to Server
      run: |
        # Set variables
        host_parameter_name="/github-action-runners/gh-runner/runners/app_instance_host"
        DEPLOY_HOST=$(aws ssm get-parameter --name "$host_parameter_name" --query "Parameter.Value" --output text)

        user_parameter_name="/github-action-runners/gh-runner/runners/app_instance_user"
        DEPLOY_USERNAME=$(aws ssm get-parameter --name "$user_parameter_name" --query "Parameter.Value" --output text)
        PRIVATE_KEY="$(<key.pem)"

        # Deploy to server using SSH
        ssh -o StrictHostKeyChecking=no -i key.pem "$DEPLOY_USERNAME@$DEPLOY_HOST" "
          # Change to the app directory
          cd /app

          # Pull the repository
          ./pull_repo.sh

          # Install npm dependencies
          npm install

          # Restart the Node.js app using pm2
          pm2 restart app.js
        "
